#include "../MainInclude.h"

// Model IDs
#define OBJ_MODEL_BOMB                          0x000
#define OBJ_MODEL_BOMB_BIG                      0x001
#define OBJ_MODEL_BOMB_RED                      0x002
#define OBJ_MODEL_BOMB_RED_BIG                  0x003
#define OBJ_MODEL_BOMB_REMOTE                   0x004
#define OBJ_MODEL_BOMB_RED_REMOTE               0x005
#define OBJ_MODEL_EXPLOSION_SPHERE              0x006
#define OBJ_MODEL_EXPLOSION_SPHERE_BLUE         0x007
#define OBJ_MODEL_EXPLOSION_SPIKES              0x008
#define OBJ_MODEL_EXPLOSION_SPIKES_BLUE         0x009
#define OBJ_MODEL_BLAST_RING                    0x00A
#define OBJ_MODEL_GREEN_LASER                   0x00B
#define OBJ_MODEL_UNKNOWN1                      0x00C
#define OBJ_MODEL_EXPLOSION_SPIKES_WHITE        0x00D
#define OBJ_MODEL_EXPLOSION_SPARKS              0x00E
#define OBJ_MODEL_EXPLOSION_SPHERE_WHITE        0x00F
#define OBJ_MODEL_EXPLOSION_SPHERE_RED          0x010
#define OBJ_MODEL_EXPLOSION_SPHERE_RED2         0x011

#define OBJ_MODEL_ITEM_FIREPOWER_UP             0x012
#define OBJ_MODEL_ITEM_BOMB_UP                  0x013
#define OBJ_MODEL_ITEM_BOMBTYPE_RED             0x014
#define OBJ_MODEL_ITEM_BOMBTYPE_REMOTE          0x015
#define OBJ_MODEL_ITEM_HEART                    0x016
#define OBJ_MODEL_ITEM_SKULL                    0x017
#define OBJ_MODEL_ITEM_EVIL                     0x018
#define OBJ_MODEL_ITEM_GOLD_CARD                0x019
#define OBJ_MODEL_ITEM_CUSTOM_HEAD              0x01A
#define OBJ_MODEL_ITEM_CUSTOM_BODY              0x01B
#define OBJ_MODEL_ITEM_CUSTOM_ARMS              0x01C
#define OBJ_MODEL_ITEM_CUSTOM_LEGS              0x01D
#define OBJ_MODEL_ITEM_GEM_BLUE                 0x01E
#define OBJ_MODEL_ITEM_GEM_RED                  0x01F

#define OBJ_MODEL_UNKNOWN2                      0x020
#define OBJ_MODEL_UNKNOWN3                      0x021
#define OBJ_MODEL_SHADOW_ROUND_BLACK            0x022
#define OBJ_MODEL_UNKNOWN5                      0x023
#define OBJ_MODEL_UNKNOWN6                      0x024
#define OBJ_MODEL_UNKNOWN7                      0x025
#define OBJ_MODEL_UNKNOWN8                      0x026

#define OBJ_MODEL_OVERWORLD_WORLDS              0x027
#define OBJ_MODEL_UNKNOWN9                      0x028
#define OBJ_MODEL_OVERWORLD_DRAGON              0x029
#define OBJ_MODEL_OVERWORLD_WATER_HEXAGON       0x02A
#define OBJ_MODEL_OVERWORLD_CHAIN               0x02B
#define OBJ_MODEL_OVERWORLD_UI_ELEMENT          0x02C
#define OBJ_MODEL_OVERWORLD_GREEN_GARDEN        0x02D
#define OBJ_MODEL_OVERWORLD_RED_VOLCANO         0x02E
#define OBJ_MODEL_OVERWORLD_WHITE_GLACIER       0x02F
#define OBJ_MODEL_UNKNOWN11                     0x030
#define OBJ_MODEL_UNKNOWN12                     0x031
#define OBJ_MODEL_BATTLE_MENU_BORDERS           0x032
#define OBJ_MODEL_BATTLE_MENU_PLAYER_SELECT     0x033
#define OBJ_MODEL_LIGHT_BLUE_PILLAR             0x034
#define OBJ_MODEL_UNKNOWN14                     0x035
#define OBJ_MODEL_UNKNOWN15                     0x036
#define OBJ_MODEL_UNKNOWN16                     0x037
#define OBJ_MODEL_UNKNOWN17                     0x038	
#define OBJ_MODEL_UNKNOWN18                     0x039
#define OBJ_MODEL_UNKNOWN19                     0x03A
#define OBJ_MODEL_BATTLE_RESULTS_WINNER_PODIUM  0x03B
#define OBJ_MODEL_BATTLE_RESULTS_WINNER_LIGHTS  0x03C
#define OBJ_MODEL_UNKNOWN20                     0x03D
#define OBJ_MODEL_BATTLE_MODE_DRAW              0x03E
#define OBJ_MODEL_BATTLE_MODE_TIMES_UP          0x03F
#define OBJ_MODEL_BATTLE_EMBLEM                 0x040

#define OBJ_MODEL_PLAYER_BOMBERMAN              0x049

#define OBJ_MODEL_QUESTION_MARK                 0x04E
#define OBJ_MODEL_UNKNOWN21                     0x04F

#define OBJ_MODEL_CUSTOM_GOLD_VISOR             0x050
#define OBJ_MODEL_CUSTOM_SUNGLASSES             0x051
#define OBJ_MODEL_CUSTOM_CAT_HOOD               0x052
#define OBJ_MODEL_CUSTOM_DRAGON_HEAD            0x053
#define OBJ_MODEL_CUSTOM_PONYTAILS              0x054
#define OBJ_MODEL_CUSTOM_IRON_GOGGLES           0x055
#define OBJ_MODEL_CUSTOM_KNIGHT_HELMET          0x056
#define OBJ_MODEL_CUSTOM_CLOWN_SMILE            0x057
#define OBJ_MODEL_CUSTOM_CHICKEN_HEAD           0x058
#define OBJ_MODEL_CUSTOM_SAMURAI_HEAD           0x059

#define OBJ_MODEL_CUSTOM_GOLD_ARMOR             0x05A
#define OBJ_MODEL_CUSTOM_DUCK_FLOAT             0x05B
#define OBJ_MODEL_CUSTOM_CAT_TAIL               0x05C
#define OBJ_MODEL_CUSTOM_DRAGON_MAIL            0x05D
#define OBJ_MODEL_CUSTOM_DRESS                  0x05E
#define OBJ_MODEL_CUSTOM_IRON_ARMOR             0x05F
#define OBJ_MODEL_CUSTOM_KNIGHT_ARMOR           0x060
#define OBJ_MODEL_CUSTOM_KARATE_WARE            0x061
#define OBJ_MODEL_CUSTOM_ROCKING_HORSE          0x062
#define OBJ_MODEL_CUSTOM_SHOGUN_KIMONO          0x063

#define OBJ_MODEL_CUSTOM_GOLD_GLOVES_L          0x064
#define OBJ_MODEL_CUSTOM_DRILL_ARMS_L           0x065
#define OBJ_MODEL_CUSTOM_CAT_PAWS_ARMS_L        0x066
#define OBJ_MODEL_CUSTOM_DRAGON_GLOVES_L        0x067
#define OBJ_MODEL_CUSTOM_SLASH_CLAWS_L          0x068
#define OBJ_MODEL_CUSTOM_IRON_NUCKLES_L         0x069
#define OBJ_MODEL_CUSTOM_KNIGHT_SWORD_L         0x06A
#define OBJ_MODEL_CUSTOM_BOXING_GLOVES_L        0x06B
#define OBJ_MODEL_CUSTOM_CHICKEN_WINGS_L        0x06C
#define OBJ_MODEL_CUSTOM_FANS_L                 0x06D

#define OBJ_MODEL_CUSTOM_GOLD_GLOVES_R          0x06E
#define OBJ_MODEL_CUSTOM_DRILL_ARMS_R           0x06F
#define OBJ_MODEL_CUSTOM_CAT_PAWS_ARMS_R        0x070
#define OBJ_MODEL_CUSTOM_DRAGON_GLOVES_R        0x071
#define OBJ_MODEL_CUSTOM_SLASH_CLAWS_R          0x072
#define OBJ_MODEL_CUSTOM_IRON_NUCKLES_R         0x073
#define OBJ_MODEL_CUSTOM_KNIGHT_SWORD_R         0x074
#define OBJ_MODEL_CUSTOM_BOXING_GLOVES_R        0x075
#define OBJ_MODEL_CUSTOM_CHICKEN_WINGS_R        0x076
#define OBJ_MODEL_CUSTOM_FANS_R                 0x077

#define OBJ_MODEL_CUSTOM_GOLD_BOOTS_L           0x078
#define OBJ_MODEL_CUSTOM_DUCK_FEET_L            0x079
#define OBJ_MODEL_CUSTOM_CAT_PAWS_LEGS_L        0x07A
#define OBJ_MODEL_CUSTOM_DRAGON_SPIKES_L        0x07B
#define OBJ_MODEL_CUSTOM_HIGH_TOPS_L            0x07C
#define OBJ_MODEL_CUSTOM_IRON_SNEAKERS_L        0x07D
#define OBJ_MODEL_CUSTOM_KNIGHT_SHOES_L         0x07E
#define OBJ_MODEL_CUSTOM_CLOGS_L                0x07F
#define OBJ_MODEL_CUSTOM_BUBBY_SOCKS_L          0x080
#define OBJ_MODEL_CUSTOM_HIGH_HEELS_L           0x081

#define OBJ_MODEL_CUSTOM_GOLD_BOOTS_R           0x082
#define OBJ_MODEL_CUSTOM_DUCK_FEET_R            0x083
#define OBJ_MODEL_CUSTOM_CAT_PAWS_LEGS_R        0x084
#define OBJ_MODEL_CUSTOM_DRAGON_SPIKES_R        0x085
#define OBJ_MODEL_CUSTOM_HIGH_TOPS_R            0x086
#define OBJ_MODEL_CUSTOM_IRON_SNEAKERS_R        0x087
#define OBJ_MODEL_CUSTOM_KNIGHT_SHOES_R         0x088
#define OBJ_MODEL_CUSTOM_CLOGS_R                0x089
#define OBJ_MODEL_CUSTOM_BUBBY_SOCKS_R          0x08A
#define OBJ_MODEL_CUSTOM_HIGH_HEELS_R           0x08B

#define OBJ_MODEL_WOOD_CRATE                    0x08C
#define OBJ_MODEL_WOOD_CRATE_BIG                0x08D
#define OBJ_MODEL_WOOD_CRATE_TALL               0x08E
#define OBJ_MODEL_COBBLE_STONE_BLOCK            0x08F
#define OBJ_MODEL_COBBLE_STONE_BLOCK_TALL       0x090
#define OBJ_MODEL_RUNIC_BLOCK                   0x091
#define OBJ_MODEL_RUNIC_BLOCK_TALL              0x092
#define OBJ_MODEL_SPRITE_CERAMIC_POT            0x093
#define OBJ_MODEL_ORNAMENT_BLOCK                0x094
#define OBJ_MODEL_RUNIC_BLOCK_SMALL             0x095

#define OBJ_MODEL_UNKNOWN22                     0x096
#define OBJ_MODEL_SPRITE_TREE                   0x097
#define OBJ_MODEL_UNKNOWN23                     0x098
#define OBJ_MODEL_WOOD_CRATE2                   0x099
#define OBJ_MODEL_DRAINAGE_BLOCK                0x09A
#define OBJ_MODEL_FLOWER_POT                    0x09B
#define OBJ_MODEL_BRICK_BLOCK                   0x09C

#define OBJ_MODEL_ROCK_PILLAR_TALL              0x09D
#define OBJ_MODEL_ROCK_PILLAR_BIG               0x09E
#define OBJ_MODEL_FURNACE                       0x09F
#define OBJ_MODEL_UNKNOWN34                     0x0A0
#define OBJ_MODEL_WOODEN_CYLINDER_TALL          0x0A1
#define OBJ_MODEL_WOODEN_CYLINDER               0x0A2
#define OBJ_MODEL_COAL_MINECART                 0x0A3
#define OBJ_MODEL_CROSSING_SIGN                 0x0A4
#define OBJ_MODEL_METAL_PILLAR                  0x0A5
#define OBJ_MODEL_METAL_BOX                     0x0A6
#define OBJ_MODEL_METAL_LAMP_POST               0x0A7
#define OBJ_MODEL_METAL_LAMP_POST2              0x0A8
#define OBJ_MODEL_METAL_LAMP_POST3              0x0A9
#define OBJ_MODEL_METAL_LAMP_POST4              0x0AA

#define OBJ_MODEL_CAR                           0x0AB
#define OBJ_MODEL_BUS                           0x0AC
#define OBJ_MODEL_CRANE_CLAW                    0x0AD
#define OBJ_MODEL_UNKNOWN35                     0x0AE
#define OBJ_MODEL_CRANE_CABIN                   0x0AF
#define OBJ_MODEL_METAL_LAMP_POST5              0x0B0
#define OBJ_MODEL_CERBERUS_LASER_DRONE          0x0B1
#define OBJ_MODEL_ELEVATOR_PAD_GREEN            0x0B2
#define OBJ_MODEL_LASER_BRIDGE                  0x0B3
#define OBJ_MODEL_METAL_LAMP_POST6              0x0B4
#define OBJ_MODEL_RED_MISSILE_TROOPER           0x0B5
#define OBJ_MODEL_YELLOW_PYRAMID_SWITCH         0x0B6
#define OBJ_MODEL_YELLOW_PYRAMID_SWITCH2        0x0B7
#define OBJ_MODEL_UNKNOWN36                     0x0B8
#define OBJ_MODEL_LIGHT_PLANE                   0x0B9
#define OBJ_MODEL_UNKNOWN38                     0x0BA
#define OBJ_MODEL_LASER_BRIDGE2                 0x0BB
#define OBJ_MODEL_UNKNOWN39                     0x0BC
#define OBJ_MODEL_ELECTRIC_LASER                0x0BD
#define OBJ_MODEL_GREEN_SWITCH_PLATE            0x0BE
#define OBJ_MODEL_BLUE_DICE_PLATE_1             0x0BF
#define OBJ_MODEL_BLUE_DICE_PLATE_2             0x0C0
#define OBJ_MODEL_BLUE_DICE_PLATE_3             0x0C1
#define OBJ_MODEL_IRON_GATE                     0x0C2
#define OBJ_MODEL_METAL_LAMP_POST7              0x0C3
#define OBJ_MODEL_BLUE_DICE_PLATE_4             0x0C4
#define OBJ_MODEL_UNKNOWN40                     0x0C5
#define OBJ_MODEL_UNKNOWN41                     0x0C6
#define OBJ_MODEL_ELEVATOR_ROOM                 0x0C7
#define OBJ_MODEL_IRON_DOOR                     0x0C8
#define OBJ_MODEL_UNKNOWN42                     0x0C9
#define OBJ_MODEL_ELEVATOR_PAD_BLACK            0x0CA
#define OBJ_MODEL_TARGET_LOCK_ON                0x0CB
#define OBJ_MODEL_TARGET_SEARCHING              0x0CC
#define OBJ_MODEL_UNKNOWN43                     0x0CD
#define OBJ_MODEL_UNKNOWN44                     0x0CE

#define OBJ_MODEL_RAINBOW_PILLAR                0x0CF
#define OBJ_MODEL_RAINBOW_BOX_BIG               0x0D0

#define OBJ_MODEL_BATTLE_ORNAMENT_BOX           0x0D1
#define OBJ_MODEL_BATTLE_TORNADO                0x0D2
#define OBJ_MODEL_BATTLE_BOULDER                0x0D3
#define OBJ_MODEL_BATTLE_FRAMED_STONE_BLOCK     0x0D4
#define OBJ_MODEL_BATTLE_SAND_STONE_BLOCK       0x0D5
#define OBJ_MODEL_BATTLE_BRICK_STONE_BLOCK      0x0D6
#define OBJ_MODEL_BATTLE_BOULDER2               0x0D7
#define OBJ_MODEL_BATTLE_BRICK_STONE_BLOCK2     0x0D8
#define OBJ_MODEL_BATTLE_WOOD_BARREL            0x0D9
#define OBJ_MODEL_BATTLE_ICICLE                 0x0DA
#define OBJ_MODEL_BATTLE_FRAMED_METAL_BLOCK     0x0DB

#define OBJ_MODEL_UNKNOWN46                     0x0DC
#define OBJ_MODEL_UNKNOWN47                     0x0DD

#define OBJ_MODEL_ENM_RED_TROOPER               0x0DE
#define OBJ_MODEL_ENM_RED_TROOPER2              0x0DF
#define OBJ_MODEL_ENM_BLUE_TROOPER              0x0E0
#define OBJ_MODEL_ENM_GREEN_TROOPER             0x0E1
#define OBJ_MODEL_ENM_FLARE_BIRD                0x0E2
#define OBJ_MODEL_ENM_TOTEM                     0x0E3
#define OBJ_MODEL_ENM_MASH                      0x0E4
#define OBJ_MODEL_ENM_BUTTERFLY                 0x0E5
#define OBJ_MODEL_ENM_GUARD                     0x0E6
#define OBJ_MODEL_ENM_BLUE_FISH                 0x0E7
#define OBJ_MODEL_ENM_BLUE_FISH_WALKING         0x0E8
#define OBJ_MODEL_ENM_JELLY_FISH                0x0E9
#define OBJ_MODEL_ENM_TROUBLEMAKER              0x0EA
#define OBJ_MODEL_ENM_FIRE_SPIKE                0x0EB
#define OBJ_MODEL_ENM_PICK                      0x0EC
#define OBJ_MODEL_ENM_BAT                       0x0ED
#define OBJ_MODEL_ENM_SPIN_SPIKE                0x0EE
#define OBJ_MODEL_ENM_MISSILE_TROOPER           0x0EF
#define OBJ_MODEL_ENM_SNOWMAN                   0x0F0
#define OBJ_MODEL_ENM_SNOW_RABBIT               0x0F1
#define OBJ_MODEL_ENM_PENGUIN                   0x0F2
#define OBJ_MODEL_ENM_FREEZY                    0x0F3
#define OBJ_MODEL_ENM_SNOWFLAKE                 0x0F4
#define OBJ_MODEL_ENM_EGGY                      0x0F5
#define OBJ_MODEL_ENM_CANNON_MECH               0x0F6
#define OBJ_MODEL_ENM_HUMANOID_TEST             0x0F7
#define OBJ_MODEL_ENM_UFO                       0x0F8
#define OBJ_MODEL_ENM_DIVE_MECH                 0x0F9
#define OBJ_MODEL_ENM_GREEN_MASK                0x0FA
#define OBJ_MODEL_ENM_HEART_KING                0x0FB
#define OBJ_MODEL_ENM_SPADE_KNIGHT              0x0FC
#define OBJ_MODEL_ENM_DIAMOND_SOLDIER           0x0FD
#define OBJ_MODEL_ENM_CLUB_FIGHTER              0x0FE
#define OBJ_MODEL_ENM_ELEKI                     0x0FF
#define OBJ_MODEL_ENM_HUMANOID_TEST2            0x100
#define OBJ_MODEL_ENM_ALARM_ROBOT               0x101

#define OBJ_MODEL_PROJECTILE_BULLET             0x102
#define OBJ_MODEL_PROJECTILE_FILLED_RING        0x103
#define OBJ_MODEL_UNKNOWN48                     0x104
#define OBJ_MODEL_PROJECTILE_SNOWBALL           0x105
#define OBJ_MODEL_PROJECTILE_MISSILE            0x106
#define OBJ_MODEL_UNKNOWN49                     0x107
#define OBJ_MODEL_UNKNOWN50                     0x108
#define OBJ_MODEL_PROJECTILE_RING               0x109
#define OBJ_MODEL_PROJECTILE_BULLET_TRIPLE      0x10A

#define OBJ_MODEL_EFFECT_SEEING_STARS           0x116
#define OBJ_MODEL_EFFECT_HEART                  0x117

#define OBJ_MODEL_EFFECT_GOAL_ARROW             0x11C

#define OBJ_MODEL_EFFECT_PLASMA_SPINNER         0x12A
#define OBJ_MODEL_EFFECT_ELECTRIC_CLOUD         0x12B
#define OBJ_MODEL_EFFECT_PUFFY_CLOUD            0x12C
#define OBJ_MODEL_EFFECT_PUFFY_CLOUD2           0x12D
#define OBJ_MODEL_EFFECT_PUFFY_CLOUD3           0x12E
#define OBJ_MODEL_EFFECT_PUFFY_CLOUD4           0x12F

#define OBJ_MODEL_UNKNOWN51                     0x130
#define OBJ_MODEL_UNKNOWN52                     0x131
#define OBJ_MODEL_MAP_TEST1                     0x132
#define OBJ_MODEL_UNKNOWN53                     0x133
#define OBJ_MODEL_MAP_TEST2                     0x134
#define OBJ_MODEL_UNKNOWN54                     0x135
#define OBJ_MODEL_MAP_TEST3                     0x136
#define OBJ_MODEL_UNKNOWN55                     0x137
#define OBJ_MODEL_MAP_TEST4                     0x138
#define OBJ_MODEL_UNKNOWN56                     0x139
#define OBJ_MODEL_MAP_BLUE_RESORT1              0x13A
#define OBJ_MODEL_MAP_BLUE_RESORT2              0x13B
#define OBJ_MODEL_MAP_BLUE_RESORT3              0x13C
#define OBJ_MODEL_MAP_BLUE_RESORT4              0x13D
#define OBJ_MODEL_MAP_BLUE_RESORT5              0x13E
#define OBJ_MODEL_MAP_BLUE_RESORT6              0x13F

#define OBJ_MODEL_MAP_UP_AND_DOWN1              0x202
#define OBJ_MODEL_MAP_UP_AND_DOWN2              0x203
#define OBJ_MODEL_MAP_UP_AND_DOWN_WATER_PLANE   0x204
#define OBJ_MODEL_MAP_UP_AND_DOWN_UNUSED        0x205
#define OBJ_MODEL_MAP_PYRAMID                   0x206

#define OBJ_MODEL_MAP_WHITE_CLACIER1            0x230
#define OBJ_MODEL_MAP_WHITE_CLACIER2            0x231

#define OBJ_MODEL_SNOWBOARD_TROOPER             0x259
//#define OBJ_MODEL_MAP_BOMB                    0x25A
#define OBJ_MODEL_BREAKABLE_SNOW_COVER         	0x25B
#define OBJ_MODEL_BREAKABLE_SNOWY_TREE         	0x25C
#define OBJ_MODEL_BREAKABLE_ICICLE_REFLECTION	0x25D
//#define OBJ_MODEL_MAP_BOMB                    0x25E
#define OBJ_MODEL_BLOCK_HOUSE_WALLS             0x25F
#define OBJ_MODEL_BLOCK_HOUSE_ROOF              0x260
#define OBJ_MODEL_SKI_LIFT_STATION            	0x261
#define OBJ_MODEL_SKI_LIFT_ELEVATOR            	0x262
//#define OBJ_MODEL_MAP_BOMB                    0x263
#define OBJ_MODEL_BREAKABLE_PINE_TREE         	0x264
#define OBJ_MODEL_ROLLING_SNOWBALL              0x265
//#define OBJ_MODEL_MAP_BOMB                    0x266
//#define OBJ_MODEL_MAP_BOMB                    0x267
#define OBJ_MODEL_BG_GLACIER_BOSS_LAIR          0x268
#define OBJ_MODEL_SNOW_AVALANCHE                0x269
#define OBJ_MODEL_FROZEN_WOODEN_SIGN            0x26A
//#define OBJ_MODEL_UNKNOWN                     0x26B
#define OBJ_MODEL_SNOW_PLATE                    0x26C
#define OBJ_MODEL_CAVE_FLOWERS1                 0x26D
#define OBJ_MODEL_CAVE_FLOWERS2                 0x26E
//#define OBJ_MODEL_MAP_BOMB                    0x26F
//#define OBJ_MODEL_MAP_BOMB                    0x270
//#define OBJ_MODEL_MAP_BOMB                    0x271
//#define OBJ_MODEL_MAP_BOMB                    0x272
//#define OBJ_MODEL_MAP_BOMB                    0x273
//#define OBJ_MODEL_MAP_BOMB                    0x274
//#define OBJ_MODEL_UNKNOWN                     0x275
//#define OBJ_MODEL_UNKNOWN                     0x276
//#define OBJ_MODEL_UNKNOWN                     0x277
//#define OBJ_MODEL_UNKNOWN                     0x278

#define OBJ_MODEL_BATTLE_TROUBLEMAKER           0x2B2


#define OBJ_MODEL_SPELLMAKER_FACE               0x2E9
#define OBJ_MODEL_SPELLMAKER_CAP                0x2EA
#define OBJ_MODEL_SPELLMAKER_UNKNOWN1           0x2EB
#define OBJ_MODEL_SPELLMAKER_CAP_BELL           0x2EC
#define OBJ_MODEL_SPELLMAKER_BELT               0x2ED
#define OBJ_MODEL_SPELLMAKER_TORSO              0x2EE
#define OBJ_MODEL_SPELLMAKER_FOOT               0x2EF
#define OBJ_MODEL_SPELLMAKER_MASK               0x2F0
#define OBJ_MODEL_SPELLMAKER_SHADOW_PLANE       0x2F1
#define OBJ_MODEL_SPELLMAKER_SHADOW_FIGURE      0x2F2
#define OBJ_MODEL_SPELLMAKER_CAPE1              0x2F3
#define OBJ_MODEL_SPELLMAKER_CAPE2              0x2F4
#define OBJ_MODEL_SPELLMAKER_CAPE3              0x2F5
#define OBJ_MODEL_SPELLMAKER_CAPE4              0x2F6
#define OBJ_MODEL_SPELLMAKER_UNKNOWN2           0x2F7
#define OBJ_MODEL_SPELLMAKER_UNKNOWN3           0x2F8
#define OBJ_MODEL_SPELLMAKER_CARD_MOON          0x2F9
#define OBJ_MODEL_SPELLMAKER_CARD_LOVERS        0x2FA
#define OBJ_MODEL_SPELLMAKER_CARD_DEATH         0x2FB
#define OBJ_MODEL_SPELLMAKER_CARD_EVIL          0x2FC
#define OBJ_MODEL_SPELLMAKER_CARD_STAR          0x2FD
#define OBJ_MODEL_SPELLMAKER_CARD_SUN           0x2FE
#define OBJ_MODEL_SPELLMAKER_CARD_WORLD         0x2FF
#define OBJ_MODEL_SPELLMAKER_CARD_DAGGER        0x300
#define OBJ_MODEL_SPELLMAKER_ARMS               0x301
#define OBJ_MODEL_SPELLMAKER_ORANGE_SPHERE      0x302
#define OBJ_MODEL_SPELLMAKER_BLUE_SPHERE        0x303
#define OBJ_MODEL_SPELLMAKER_DARK_LIGHT_CIRCLE  0x304
#define OBJ_MODEL_SPELLMAKER_FIRE_DRAGON_HEAD   0x305
#define OBJ_MODEL_SPELLMAKER_STAR               0x306
#define OBJ_MODEL_SPELLMAKER_LIGHT_CIRCLE       0x307
#define OBJ_MODEL_SPELLMAKER_SMASH_FOOT         0x308
#define OBJ_MODEL_SPELLMAKER_SMASH_FIST_R       0x309
#define OBJ_MODEL_SPELLMAKER_SMASH_FIST_L       0x30A
#define OBJ_MODEL_SPELLMAKER_GRAB_HAND          0x30B
#define OBJ_MODEL_SPELLMAKER_UNKNOWN4           0x30C
#define OBJ_MODEL_SPELLMAKER_GREEN_PLANE_S      0x30D
#define OBJ_MODEL_SPELLMAKER_GREEN_PLANE_M      0x30E
#define OBJ_MODEL_SPELLMAKER_GREEN_PLANE_L      0x30F
#define OBJ_MODEL_SPELLMAKER_GREEN_PLANE_XL     0x310
#define OBJ_MODEL_SPELLMAKER_GREEN_PLANE_XXL    0x311
#define OBJ_MODEL_SPELLMAKER_ITEM_16T_WEIGHT    0x312
#define OBJ_MODEL_SPELLMAKER_ITEM_STAFF         0x313
#define OBJ_MODEL_SPELLMAKER_ITEM_DAGGER        0x314
#define OBJ_MODEL_SPELLMAKER_ITEM_BOMB_UP_EVIL  0x315

#define OBJ_MODEL_PLAYER_ARTEMIS                0x320
#define OBJ_MODEL_PLAYER_ORION                  0x321
#define OBJ_MODEL_PLAYER_REGULUS                0x322
#define OBJ_MODEL_PLAYER_SIRIUS                 0x323
#define OBJ_MODEL_PLAYER_ALTAIR                 0x324

#define OBJ_MODEL_PLAYER_ALTAIR_ARMOR           0x326
#define OBJ_MODEL_PLAYER_ALTAIR_GEAR            0x327
#define OBJ_MODEL_PLAYER_SIRIUS_ARMOR           0x328
#define OBJ_MODEL_ATTACK_SIRIUS_DRAGON_JET      0x329
#define OBJ_MODEL_PROJECTILE_ARTEMIS_FLARE      0x32A
#define OBJ_MODEL_UNKNOWN58                     0x32B
#define OBJ_MODEL_EFFECT_ORION_SMOKE_CLOUDS     0x32C
#define OBJ_MODEL_EFFECT_ORION_GREEN_DOME       0x32D
#define OBJ_MODEL_PROJECTILE_REGULUS_SWOOSH     0x32E
#define OBJ_MODEL_PROJECTILE_ALTAIR_SLASH       0x32F

#define OBJ_MODEL_INTRO_GRASS_PLANE             0x33A
#define OBJ_MODEL_INTRO_UNKNOWN1                0x33B
#define OBJ_MODEL_INTRO_ROUND_RACCOON           0x33C
#define OBJ_MODEL_INTRO_ROUND_MOUSE             0x33D
#define OBJ_MODEL_INTRO_SMALL_BIRD              0x33E
#define OBJ_MODEL_INTRO_UNKNOWN2                0x33F
#define OBJ_MODEL_INTRO_PLANET_BOMBER           0x340
#define OBJ_MODEL_INTRO_GREEN_VERTICAL_BEAM     0x341
#define OBJ_MODEL_INTRO_HOLO_PODIUM             0x342
#define OBJ_MODEL_INTRO_UNKNOWN3                0x343
#define OBJ_MODEL_INTRO_UNKNOWN4                0x344
#define OBJ_MODEL_INTRO_WINDMILL                0x345
#define OBJ_MODEL_INTRO_OMNI_CUBE               0x346
#define OBJ_MODEL_INTRO_PLANET_BOMBER2          0x347
#define OBJ_MODEL_INTRO_PLANET_BOMBER3          0x348
#define OBJ_MODEL_INTRO_PLANET_BOMBER4          0x349
#define OBJ_MODEL_INTRO_PLANET_BOMBER5          0x34A
#define OBJ_MODEL_INTRO_UNKNOWN5                0x34B
#define OBJ_MODEL_INTRO_UNKNOWN6                0x34C
#define OBJ_MODEL_INTRO_UNKNOWN7                0x34D
#define OBJ_MODEL_INTRO_UNKNOWN8                0x34E
#define OBJ_MODEL_TOTEM                         0x34F
#define OBJ_MODEL_BATTLE_MAP_MANTA              0x350
#define OBJ_MODEL_BATTLE_MAP_FISH               0x351
#define OBJ_MODEL_BATTLE_MAP_LOST_AT_SEA1       0x352
#define OBJ_MODEL_UNKNOWN60                     0x353







